# This is a basic workflow to help you get started with Actions

name: Test kubesec

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  minikube-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: opsgang/ga-setup-minikube@v0.1.1
      with:
        minikube-version: 1.12.0
        k8s-version: 1.15.1
    - name: Testing
      run: |
        cd tests
        curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | sh
        source ~/.nvm/nvm.sh
        which kubectl

